"""remove present and permanent address

Revision ID: bc83c218d6b5
Revises: 1297a549e631
Create Date: 2026-04-10 23:13:32.508797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc83c218d6b5'
down_revision = '1297a549e631'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'present_address')
    op.drop_column('candidates', 'permanent_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('permanent_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('present_address', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###