"""Add company_employees table

Revision ID: d70ffdd1f248
Revises: 6bfd8de3219c
Create Date: 2026-04-01 23:57:38.441386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd70ffdd1f248'
down_revision = '6bfd8de3219c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_client_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.alter_column('applications', 'application_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_applications_candidate_id'), table_name='applications')
    op.drop_index(op.f('idx_applications_client_id'), table_name='applications')
    op.drop_index(op.f('idx_applications_deleted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_applied_by_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.alter_column('candidates', 'previous_employment',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('candidates', 'experience',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('candidates', 'is_direct_interview',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_candidates_assigned_user_id'), table_name='candidates')
    op.drop_index(op.f('idx_candidates_client_id'), table_name='candidates')
    op.drop_index(op.f('idx_candidates_email'), table_name='candidates')
    op.drop_index(op.f('idx_candidates_hash'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_source'), table_name='candidates')
    op.create_foreign_key(None, 'candidates', 'users', ['assigned_user_id'], ['id'])
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('fsm_transition_logs', 'is_terminal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('fsm_transition_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_fsm_transition_logs_candidate_id'), table_name='fsm_transition_logs')
    op.drop_index(op.f('idx_fsm_transition_logs_client_id'), table_name='fsm_transition_logs')
    op.drop_index(op.f('idx_fsm_transition_logs_created_at'), table_name='fsm_transition_logs')
    op.drop_index(op.f('idx_interview_records_candidate_id'), table_name='interview_records')
    op.drop_index(op.f('idx_interview_records_client_id'), table_name='interview_records')
    op.drop_index(op.f('idx_interview_records_company_id'), table_name='interview_records')
    op.drop_index(op.f('idx_interview_records_created_at'), table_name='interview_records')
    op.drop_index(op.f('idx_interview_records_deleted_at'), table_name='interview_records')
    op.drop_index(op.f('idx_interview_records_interviewer_id'), table_name='interview_records')
    op.drop_index(op.f('uq_interview_records_candidate_company_date_active'), table_name='interview_records', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_jobs_client_id'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_company_name'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_location'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_title'), table_name='jobs')
    op.create_index(op.f('ix_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.drop_index(op.f('idx_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', type_='unique')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.alter_column('resume_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_resume_jobs_client_id'), table_name='resume_jobs')
    op.drop_index(op.f('idx_resume_jobs_status'), table_name='resume_jobs')
    op.drop_index(op.f('ix_security_audit_logs_created_at'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_email'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_type'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_ip_address'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_severity'), table_name='security_audit_logs')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_active'), table_name='users')
    op.drop_index(op.f('idx_users_client_id'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_index(op.f('idx_users_active'), 'users', ['is_active'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_security_audit_logs_severity'), 'security_audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_ip_address'), 'security_audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_email'), 'security_audit_logs', ['email'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_created_at'), 'security_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_resume_jobs_status'), 'resume_jobs', ['status'], unique=False)
    op.create_index(op.f('idx_resume_jobs_client_id'), 'resume_jobs', ['client_id'], unique=False)
    op.alter_column('resume_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_client_id'), table_name='jobs')
    op.create_index(op.f('idx_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('idx_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('idx_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('idx_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_index(op.f('uq_interview_records_candidate_company_date_active'), 'interview_records', ['candidate_id', 'company_id', 'interview_date'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_interview_records_interviewer_id'), 'interview_records', ['interviewer_id'], unique=False)
    op.create_index(op.f('idx_interview_records_deleted_at'), 'interview_records', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_interview_records_created_at'), 'interview_records', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_interview_records_company_id'), 'interview_records', ['company_id'], unique=False)
    op.create_index(op.f('idx_interview_records_client_id'), 'interview_records', ['client_id'], unique=False)
    op.create_index(op.f('idx_interview_records_candidate_id'), 'interview_records', ['candidate_id'], unique=False)
    op.create_index(op.f('idx_fsm_transition_logs_created_at'), 'fsm_transition_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_fsm_transition_logs_client_id'), 'fsm_transition_logs', ['client_id'], unique=False)
    op.create_index(op.f('idx_fsm_transition_logs_candidate_id'), 'fsm_transition_logs', ['candidate_id'], unique=False)
    op.alter_column('fsm_transition_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fsm_transition_logs', 'is_terminal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_index(op.f('ix_candidates_source'), 'candidates', ['source'], unique=False)
    op.create_index(op.f('idx_candidates_hash'), 'candidates', ['candidate_hash'], unique=False)
    op.create_index(op.f('idx_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('idx_candidates_client_id'), 'candidates', ['client_id'], unique=False)
    op.create_index(op.f('idx_candidates_assigned_user_id'), 'candidates', ['assigned_user_id'], unique=False)
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'is_direct_interview',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('candidates', 'experience',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('candidates', 'previous_employment',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_applied_by_user_id'), 'applications', ['applied_by_user_id'], unique=False)
    op.create_index(op.f('idx_applications_deleted_at'), 'applications', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_applications_client_id'), 'applications', ['client_id'], unique=False)
    op.create_index(op.f('idx_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'application_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_client_id'), 'activity_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('audit_logs_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    # ### end Alembic commands ###