"""add_user_role

Revision ID: edf1ed5dfbab
Revises: 004
Create Date: 2026-02-16 21:18:10.736352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edf1ed5dfbab'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='client_user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('users', 'role')
    # ### end Alembic commands ###

    # ### end Alembic commands ###